### ISSUE TITLE
Improvement of installation documentation

### ISSUE THREAD

**Issue by mfaltas-sandia** [MHKiT-Software/MHKiT#35]
**1.** The link to the Anaconda distribution refers to the anaconda distribution with python 3.8. Meanwhile, MHKiT only works with python 3.6 and 3.7. A link to an anaconda distribution with python 3.6 or 3.7 is needed to replace the current link.

![image](https://user-images.githubusercontent.com/70349387/95141163-b1a16800-072d-11eb-919d-34f67f50440b.png)

**2.** The "Check the MATLAB Environment for Python" section recommends skipping to the "Install the MHKiT-MATLAB Toolbox" section if the python version is 3.6+. This statement is highlighted in the red box below

There are two issue with that statement:

_First,_ MHKiT only works with Python 3.6 and 3.7; It does NOT work with 3.8. Instead of "3.6+", the doc should only say that 3.6 and 3.7 are good and all other versions of python are bad - as far as MHKiT is concerned.

_Second,_ The following section is _NOT_ titled "Install the MHKiT-MATLAB Toolbox" section, Instead, it is titled "Install the MHKiT-MATLAB Toolbox (mhkit.mltbx)". Installing the MHKiT-MATLAB toolbox is critical to the operation of the MHKiT package and users often miss that step. While documentation is correct, clarifying the name better might alert users to the importance of the following step.

![image](https://user-images.githubusercontent.com/70349387/95140736-cd583e80-072c-11eb-86d5-a4ff620fa456.png)

**3.** To avoid users skipping the "Install the MHKiT-MATLAB Toolbox (mhkit.mltbx)" step, a screen shot of what the user should see can be added to the documentation. An example of such screen shot is added below:

![image](https://user-images.githubusercontent.com/70349387/95141448-7489a580-072e-11eb-84cc-5baed3ee48e8.png)

![image](https://user-images.githubusercontent.com/70349387/95141540-badf0480-072e-11eb-8c11-d43e84295eb7.png)

**Comment by ssolson** [comment]
Mina,

It looks like you are working on an outdated version of the documentation. Please review the latest documentation here: https://mhkit-software.github.io/MHKiT/installation.html

MHKiT DOES work with 3.8 we CI test this on every push. See https://travis-ci.org/github/MHKiT-Software/MHKiT-Python.

MATLAB R2020b and higher work with Python 3.8. we do need to add a note about this.

**Comment by kmruehl** [comment]
@mfaltas-sandia and @ssolson this issue directly relates to the recently merged https://github.com/MHKiT-Software/MHKiT/pull/34 from @rpauly18. 

For a little background, Mina is setting up and running the MHKiT-MATLAB tests on the Jenkins server. This is how he ran into a MATLAB/Python compatibility issue, because he was running MATLAB 2020a and Python 3.8. Rebecca has since added a note in the documentation highlighting this issue. When reviewing https://github.com/MHKiT-Software/MHKiT/pull/34 I also made some changes to the installation instructions, hopefully these clarify installation for both Python and MATLAB. 

@mfaltas-sandia can you please review the updated documentation, and if/when you see anything that is unclear, please fork this repository into your user account, make revisions there, and then submit a pull-request. Thank you!
